### ISSUE TITLE
login error to repo

### ISSUE THREAD

**Issue by MyraBaba** [jaigouk/storm_wiki#15]
asking user name password

git clone https://github.com/yourusername/storm-minimal-ui.git

**Comment by jaigouk** [comment]
either `git clone https://github.com/jaigouk/storm_wiki.git` or fork the repo then `git clone git@github.com:MyraBaba/storm_wiki.git`

**Comment by MyraBaba** [comment]
git clone git@github.com:MyraBaba/storm_wiki.git
Cloning into 'storm_wiki'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

is git clone https://github.com/jaigouk/storm_wiki.git is enough do we need storm-minimal-ui git ?

**Comment by jaigouk** [comment]
i will fix the readme. 
assuming that you already have python env(like conda https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html)

```
git clone https://github.com/jaigouk/storm_wiki.git
cd storm_wiki

cp .env.example .env
cp secrets.toml.example ./.streamlit/secrets.toml

# update .env and secrets.toml with vscode or any other editor

pip install -r requirements.txt
streamlit run storm.py --server.port 8501 --server.address 0.0.0.0

```

after this is done within terminal, now you can visit http://localhost:8501/ with a browser.

**Comment by jaigouk** [comment]
@MyraBaba updated readme https://github.com/jaigouk/storm_wiki/blob/1d749aaa724a661ba45c9a747587000aa99e47b8/README.md

**Comment by MyraBaba** [comment]
@jaigouk 

now this error:


sqlite3.OperationalError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/home/bc/Projects/ODS/storm_wiki/venvStormWiki/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
File "/home/bc/Projects/ODS/storm_wiki/storm.py", line 9, in <module>
    from pages_util.CreateNewArticle import create_new_article_page
File "/home/bc/Projects/ODS/storm_wiki/pages_util/CreateNewArticle.py", line 21, in <module>
    categories = FileIOHelper.load_categories()
File "/home/bc/Projects/ODS/storm_wiki/util/file_io.py", line 48, in load_categories
    c.execute("SELECT value FROM settings WHERE key='categories'")


-----------

streamlit run storm.py --server.port 8509 --server.address 0.0.0.0
WARNING: Static file serving is enabled, but no static folder found at /home/bc/Projects/ODS/storm_wiki/static. To disable static file serving, set server.enableStaticServing to false.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8509

phoenix.config : INFO     : 📋 Ensuring phoenix working directory: /home/bc/.phoenix
phoenix.inferences.inferences : INFO     : Dataset: phoenix_inferences_9d1c8b2c-84a1-4a10-9a3f-f253c397154f initialized
2024-08-06 23:54:27.943 Uncaught app exception
Traceback (most recent call last):
  File "/home/bc/Projects/ODS/storm_wiki/venvStormWiki/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/home/bc/Projects/ODS/storm_wiki/storm.py", line 9, in <module>
    from pages_util.CreateNewArticle import create_new_article_page
  File "/home/bc/Projects/ODS/storm_wiki/pages_util/CreateNewArticle.py", line 21, in <module>
    categories = FileIOHelper.load_categories()
  File "/home/bc/Projects/ODS/storm_wiki/util/file_io.py", line 48, in load_categories
    c.execute("SELECT value FROM settings WHERE key='categories'")
sqlite3.OperationalError: no such table: settings

**Comment by jaigouk** [comment]
let me look into this.

**Comment by jaigouk** [comment]
@MyraBaba i found the issue and pushed to main branch https://github.com/jaigouk/storm_wiki/commit/9ffe58dc7ff7d1847cf4fdab39a357be83eb5e88
